# Site
name: "Dhammarato Dhamma"
title: "Dhammarato Dhamma"
description: "An Archive of Dhammarato's Dhamma Talks"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ""
url: "https://dhammarato.com"
google_analytics: 'G-T5LXCB4934'
disqus: 'dhammarato-dhamma'
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  Dhammarato:
    name: Dhammarato Dhamma
    display_name: Dhammarato
    gravatar: 9fd99402c6a3b974ce8a250f5cfc33bd
    email: dhammaratog@gmail.com
    web: https://opensanghafoundation.org/
    twitter: https://twitter.com/dhammarato
    description: "Dhammarato is a dhamma teacher in the lineage of Bhikkhu Buddhadasa. Now retired into the Lay life He spent many years as a monk in both Thailand and USA. He lives in Thailand on Kho Phangan and invites all dhamma friends to come hang out. He talks about the supramundane dhamma as instructed by Achan Pho the abbot of Wat Suan Mokkh."
  Dhammarato:
    name: Dhammarato
    display_name: Dhammarato
    gravatar: 9fd99402c6a3b974ce8a250f5cfc33bd
    email: dhammaratog@gmail.com
    web: https://opensanghafoundation.org/
    twitter: https://twitter.com/dhammarato
    description: "Dhammarato is a dhamma teacher in the lineage of Bhikkhu Buddhadasa. Now retired into the Lay life He spent many years as a monk in both Thailand and USA. He lives in Thailand on Kho Phangan and invites all dhamma friends to come hang out. He talks about the supramundane dhamma as instructed by Achan Pho the abbot of Wat Suan Mokkh."
  Chris T.:
    name: Chris
    display_name: Chris T.    
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
